sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t h0ll0h/docker-react -f Dockerfile.dev . 
script:
  - docker run -e CI=true h0ll0h/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-new"
  env: "Dockernew-env"
  bucket_name: "elasticbeanstalk-ap-south-1-310803995000"
  bucket_path: "docker-new"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
